# Generated by Django 4.2.7 on 2024-02-10 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='custom_field',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=1, max_length=17, validators=[django.core.validators.RegexValidator(message='Телефонный номер должен соответствовать формату +996 XXX XXX XXX', regex='^\\+996 \\d{3} \\d{3} \\d{3}$')]),
            preserve_default=False,
        ),
    ]
