# Generated by Django 4.2.7 on 2024-02-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='advert_status',
            field=models.CharField(choices=[('moderation', 'модерация'), ('published', 'опубликовано'), ('canceled', 'отклонено'), ('deleted', 'удалено')], default='moderation', max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='updated',
            field=models.DateTimeField(verbose_name='Updated at'),
        ),
    ]
