# Generated by Django 4.2.7 on 2024-02-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_advert_advert_status_alter_advert_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='advert_status',
            field=models.CharField(choices=[('moderation', 'модерация'), ('published', 'опубликовано'), ('canceled', 'отклонено'), ('deleted', 'удалено')], default='moderation', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Category'),
        ),
    ]
