# Generated by Django 4.2.7 on 2024-02-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_advert_advert_status_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published at'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at'),
        ),
    ]
