# Generated by Django 4.2.7 on 2024-02-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_advert_published_alter_advert_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='published',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Published at'),
        ),
    ]
